### ISSUE TITLE
程序在输入node index.js yourId后无反应

### ISSUE THREAD

**Issue by JasonCheung811** [GeorgeChen-666/epubeeDownloader#1]
PS C:\Users\LENOVO\Downloads\Compressed\epubeeDownloader-master> npm i
audited 513 packages in 2.614s

2 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\LENOVO\Downloads\Compressed\epubeeDownloader-master> npm audit                                              
                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   chromeless

  Path            chromeless > chrome-launcher > mkdirp > minimist

  More info       https://npmjs.com/advisories/1179

found 1 low severity vulnerability in 513 scanned packages
  1 vulnerability requires manual review. See the full report for details.
PS C:\Users\LENOVO\Downloads\Compressed\epubeeDownloader-master> node index.js 38072214

**Comment by GeorgeChen-666** [comment]
你好yourId应该是你的epubee账号，另外程序是在半夜自动下载电子书的，你要一直开着它。
